[general]
exp_name: multiarith_pot_gpt4_full

# Dataset parameters
[dataset]
name: multiarith
indicies: [0,1,2]

# Method parameters
[method]
name: PoT
n_runs: 1
max_new_tokens: 256
prompting: zs

# Model parameters
[model]
name: gpt-4o-2024-05-13
use_gpu: False

# Metric parameters # k=1 because it is greedy!!
[metric]
name: pass@k
n: 1
k: 1
