[general]
exp_name: multiarith_cot-auto_llama-3-70_full

# Dataset parameters
[dataset]
name: multiarith
indicies: [0,1,2]

# Method parameters
[method]
name: AutoCoT
n_runs: 1
max_new_tokens: 200

# Model parameters
[model]
name: llama-3-70B
use_gpu: True
gpu_ids: [0,2]
max_new_tokens: 200

# Metric parameters
[metric]
name: pass@k
n: 10
k: 3
