[general]
exp_name: multiarith_cot-sc_llama-3-70_full

# Dataset parameters
[dataset]
name: multiarith
indicies: [0,1,2]

# Method parameters
[method]
name: SelfConsistencyCoT
n_runs: 10
max_new_tokens: 200

# Model parameters
[model]
name: llama-3-70B
use_gpu: True
gpu_ids: [1,3]
max_new_tokens: 200

# Metric parameters
[metric]
name: pass@k
n: 5
k: 3
