[general]
exp_name: math_cot_gpt4_full

# Dataset parameters
[dataset]
name: math
indicies: [0]

# Method parameters
[method]
name: CoT
n_runs: 1
max_new_tokens: 256
strategy: first

# Model parameters
[model]
name: gpt-4o-2024-05-13
use_gpu: False

# Metric parameters
[metric]
name: pass@k
k: 3
n: 5
