[general]
exp_name: math_cot-sc_llama-3-70_full

# Dataset parameters
[dataset]
name: math
indicies: [0]

# Method parameters
[method]
name: SelfConsistencyCoT
n_runs: 10
max_new_tokens: 256
strategy: first
shots: 8

# Model parameters
[model]
name: llama-3-70B
use_gpu: True
gpu_ids: [0,1]
max_new_tokens: 180

# Metric parameters
[metric]
name: pass@k
n: 5
k: 3
