[general]
exp_name: svamp_pal_gpt4_full

# Dataset parameters
[dataset]
name: svamp
indicies: None

# Method parameters
[method]
name: PAL
n_runs: 1
max_new_tokens: 200

# Model parameters
[model]
name: gpt-4o-2024-05-13
use_gpu: False

# Metric parameters
[metric]
name: pass@k
n: 5
k: 3