[general]
exp_name: aqua_cot_llama-3-70_full

# Dataset parameters
[dataset]
name: aqua
indicies: None

# Method parameters
[method]
name: CoT
n_runs: 1
max_new_tokens: 256

# Model parameters
[model]
name: llama-3-70B
use_gpu: True
gpu_ids: [0,2]
max_new_tokens: 256

# Metric parameters
[metric]
name: pass@k
n: 5
k: 3
