[general]
exp_name: gsm8k_cot_gpt4_full

# Dataset parameters
[dataset]
name: gsm8k
indicies: None

# Method parameters
[method]
name: CoT
n_runs: 1
max_new_tokens: 256

# Model parameters
[model]
name: gpt-4o-2024-05-13
use_gpu: False

# Metric parameters
[metric]
name: pass@k
n: 5
k: 3