[general]
exp_name: gsm8k_pot_gpt4_full

# Dataset parameters
[dataset]
name: gsm8k
indicies: None

# Method parameters
[method]
name: PoT
n_runs: 1
max_new_tokens: 256

# Model parameters
[model]
name: gpt-4o-2024-05-13
use_gpu: False

# Metric parameters # k=1 because it is greedy!!
[metric]
name: pass@k
k: 1
n: 1
