[general]
exp_name: gsm8k_cot-zero_llama-3-70_full

# Dataset parameters
[dataset]
name: gsm8k
indicies: None

# Method parameters
[method]
name: ZeroShotCoT
n_runs: 1
max_new_tokens: 200

# Model parameters
[model]
name: llama-3-70B
use_gpu: True
gpu_ids: [1,3]
max_new_tokens: 200

# Metric parameters
[metric]
name: pass@k
n: 5
k: 3